name: Main
on: push

jobs:
  python:
    name: 'Explore Python environment'

    runs-on: ubuntu-16.04

    steps:
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Dump sysconfig
      shell: /opt/hostedtoolcache/Python/2.7.16/x64/python
      run: |
        import sysconfig
        print(sysconfig.get_config_vars())

  bug:
    name: 'Bug with success()'

    runs-on: ubuntu-latest

    steps:
    - name: A step which succeeds
      run: exit 0

    - name: A step which fails
      run: exit 1

    - name: A step which runs unconditionally and succeeds
      if: always()
      run: exit 0

    - name: A step which should run if the last step succeeds
      if: success()
      run: exit 0
